/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_computron_rc_controller_MainActivity_DoRead */

#ifndef _Included_com_example_computron_rc_controller_MainActivity_DoRead
#define _Included_com_example_computron_rc_controller_MainActivity_DoRead
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
